Feature
Godswilly/news-week pull request #1
Opened 2020-07-03 12:32 UTC by Godswilly

2020-07-03 14:01 UTC, Godswilly commented
This is the Newsweek web page clone. I tried to work with Bootstrap and media queries to make the site responsive.

2020-07-04 01:12 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @Godswilly** 
Good job with your first submission for this project :muscle:  
your page looks really similar to the original :clap: :clap: :clap:  
Your project passes most of the requirements. Just a few details to improve before you can go ahead:
- [ ]  Use input for the search in the navbar
- [ ] For the large screen size, burger icon shouldn't appear
- [ ]  For the medium screen size, the user icon shouldn't appear. Look at the original page:

![](https://i.imgur.com/3v6DMcfl.png)

And your page:

![](https://i.imgur.com/jIOqdGbl.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-04 01:12 UTC, andresporras3423 commented on index.html
> +            <span>Search <i class="fas fa-search nav-item"></i> </span></a>
The search in the navbar should be an input

2020-07-04 08:05 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hi @Godswilly 👋. Your project looks really great! And almost looks like an exact clone 👏👌!

### But we need to work on some changes before we can move ahead.

- Your PR is empty. Please provide a description about what you have done in the project.

- Please add a margin on either side of the whole clone.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/86507747-61e29600-bdf8-11ea-8c4d-01b22436e145.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/86507765-7f176480-bdf8-11ea-9459-2d97bb16374a.png)

- Please make this look like the original.
![image](https://user-images.githubusercontent.com/57726348/86507774-95252500-bdf8-11ea-97ba-9614e16b1240.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/86507780-a1a97d80-bdf8-11ea-94cc-54c7bfc014f7.png)

- Please add some padding to these elements 👇.
![image](https://user-images.githubusercontent.com/57726348/86507957-bdf9ea00-bdf9-11ea-976c-e076f9339324.png)


- Please remove the hamburger icon from the desktop mode. It should appear in tablet mode.
![image](https://user-images.githubusercontent.com/57726348/86507844-ff3dca00-bdf8-11ea-8e79-9edde67cf81f.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/86507866-0f55a980-bdf9-11ea-91c9-f52cb7a35de0.png)

- Please fix this 👇
![image](https://user-images.githubusercontent.com/57726348/86507894-2dbba500-bdf9-11ea-9ae8-c33ade3e07a7.png)

- Decrease the space where I have marked with arrows.
![image](https://user-images.githubusercontent.com/57726348/86507925-7b381200-bdf9-11ea-9e40-57b73edcb0d2.png)

- Please fix the squeezing images 👇
![image](https://user-images.githubusercontent.com/57726348/86507989-e84ba780-bdf9-11ea-9607-40b3b256b22f.png)

- Please make this section look like the original.
![image](https://user-images.githubusercontent.com/57726348/86508022-32cd2400-bdfa-11ea-8f18-b455b0dd4876.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/86508033-4aa4a800-bdfa-11ea-82eb-7281dc33c13f.png)

- The navbar should be fixed in small screens.

#### Clone
![Annotation 2020-07-04 132919](https://user-images.githubusercontent.com/57726348/86508095-ee8e5380-bdfa-11ea-9cb9-8753a51b5ea6.jpg)

#### Original
![Annotation 2020-07-04 133051](https://user-images.githubusercontent.com/57726348/86508105-01088d00-bdfb-11ea-88ac-22bf8f1c7eda.jpg)


Apply these changes and request another review.

Happy coding 👨‍💻

2020-07-04 15:46 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello @Godswilly 👋, it's me again 😀. You are almost there.

- I see that you have tried to add a margin on both sides of your clone. But it's not behaving like the original. In the original, the page maintains a `max-width` of `1300px`. Right now your clone maintains the margin up to `1400px`. Please fix this.

- The search in the navbar should be an input field.
![image](https://user-images.githubusercontent.com/57726348/86516048-2d43fe00-be3b-11ea-916f-32539512359b.png)

- Please fix this to match the original 👇
   ![image](https://user-images.githubusercontent.com/57726348/86516073-4c429000-be3b-11ea-8c6f-6f71d4a3f0b8.png)

   #### Original
   ![image](https://user-images.githubusercontent.com/57726348/86516079-55336180-be3b-11ea-8d85-325a6a411d92.png)

### Please apply these changes and request another review.

Happy coding 👨‍💻

2020-07-04 20:48 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle:

### Hi @Godswilly :+1: 

### Your project is getting better and better, there some changes that are required:
- as requested by the previous TSE, the page should have a max width of 1300px,
clone:
![Screenshot from 2020-07-04 21-44-20](https://user-images.githubusercontent.com/26064042/86520722-94fc4800-be3f-11ea-968b-31709392c39a.png)
original:
![Screenshot from 2020-07-04 21-45-11](https://user-images.githubusercontent.com/26064042/86520728-a9404500-be3f-11ea-98ae-9db7772a9727.png)
This is two pictures are for 3600 px width.
### Once done with the changes, please ask for another code review

2020-07-04 22:31 UTC, HADDADSOHAIB approved these changes
### Status: Project Approved :+1: 

### Hi @Godswilly   :hand: 

### You did great with the project, you implemented all changes required with the previous TSEs, you can go on and merge this branch into master.

2020-07-06 07:52 UTC, merged